### ISSUE TITLE
The role does not exist in debian/buster64

### ISSUE THREAD

**Issue by anassrakibi** [geerlingguy/ansible-role-rabbitmq#5]
When I try to install the role in a debian/buster64. I get 

``` fatal: []: FAILED! => {"changed": false, "dest": "/tmp/rabbitmq-server_3.6.16-1_all.deb", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://packagecloud.io/rabbitmq/rabbitmq-server/packages/debian/buster/rabbitmq-server_3.6.16-1_all.deb/download"}```

**Comment by piotrkochan** [comment]
Just use different vars

```
rabbitmq_version: "3.7.8"

rabbitmq_deb: "rabbitmq-server_{{ rabbitmq_version }}-1_all.deb"
rabbitmq_deb_url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v{{ rabbitmq_version }}/{{ rabbitmq_deb }}"
```
