### ISSUE TITLE
Ubuntu 20.04 (focal) doesn't supported by https://packagecloud.io

### ISSUE THREAD

**Issue by assapir** [geerlingguy/ansible-role-rabbitmq#9]
When trying to run the role on Ubuntu 20.04, there is an error:
```
FAILED! => {"changed": false, "dest": "/tmp/rabbitmq-server_3.6.11-1_all.deb", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://packagecloud.io/rabbitmq/rabbitmq-server/packages/ubuntu/focal/rabbitmq-server_3.6.11-1_all.deb/download"}
```
From looking on `https://packagecloud.io` it doesn't seem like it support `focal`

**Comment by mrpandat** [comment]
Hey, I just had this issue with debian buster.
It seems that the rabbitmq 3.6.11 is not host anymore by packagecloud.
I manage to fix this by setting the rabbitmq_version at "3.7.18".

**Comment by arnoldasbet** [comment]
Same, tried on Ubuntu 18.04.5 LTS
```
TASK [geerlingguy.rabbitmq : Download RabbitMQ package.] ***************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "dest": "/tmp/rabbitmq-server_3.6.11-1_all.deb", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://packagecloud.io/rabbitmq/rabbitmq-server/packages/ubuntu/bionic/rabbitmq-server_3.6.11-1_all.deb/download"}
```

Can't it check for latest version out of the box, I would like to avoid binding specific version in my playbook unless it is specifically needed per requirements.

**Comment by RyanQuey** [comment]
Seems like this pr could help solve this as well: https://github.com/geerlingguy/ansible-role-rabbitmq/pull/12
